apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cronus.fullname" . }}
  labels:
    app: {{ template "cronus.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: {{ .Values.event.type }}
    kind: {{ .Values.event.kind }}
data:
  config.json: |
    {
      "type": "cron",
      "kind": "codefresh",
      "service-url": "http://{{ template "cronus.fullname" . }}:{{ .Values.service.externalPort }}",
      "uri-template": "cron:codefresh:{{"{{"}}expression{{"}}"}}:{{"{{"}}message{{"}}"}}:push",
      "uri-regex": "^cron:codefresh:@yearly|@annually|@montly|@weekly|@daily|@midnight|@hourly|([a-zA-Z0-9_-][a-zA-Z0-9*/,-?]+\s?){6}:[a-zA-Z0-9_-]{1,30}$",
      "config": [{
              "name": "expression",
              "type": "cron",
              "validator": "cron",
              "required": true
          },
          {
              "name": "message",
              "type": "string",
              "validator": "^[a-zA-Z0-9_-]{2,64}$",
              "required": true
          }
      ]
    }